version: '3'

services: 
  web:
    build: 
      context: ./main
    ports: 
      - "8000:8000"
    depends_on: 
      - postgres
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./main:/app
 

    env_file: 
      - ./.env

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    env_file: 
      - ./.env